name: Build
on:
  push:
    paths-ignore:
      - '*.pdf'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        extra_system_packages: texlive-latex-extra
    - name: Build LaTeX
      run: |
        echo $PWD
        ls
        cd $PWD/Blanc_FR_S01_E01
        latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -outdir=. Blanc_FR_S01_E01
        cd ..
        done
